pipebird/pipebird

lib/aws/upload.ts, lib/env.ts, lib/snowflake/connection.ts, lib/snowflake/load.ts, migrations/20220827201027_add_snowflake_to_destination_types/migration.sql, package-lock.json, package.json, schema.prisma, server/queues/transfer/processor.ts, server/routes/destinations/index.ts
- We want to start loading data directly into warehouses owned by end customers
- While CSVs serve some initial use cases, we want to make it as easy as possible to get data into the actual locations where it will be utilized
- Added handling for adding Snowflake destinations, which ensures that the proper credentials are saved and that there is a reachable connection to a user's account
- Also perform upsert operations in a queue job to get data into Snowflake using CSVs in S3
- Ran through a manual test by using a local Postgres source and a Snowflake destination
- Stress tested by using a configuration that only selected a subset of data from the provided view
- Changed underlying data in the source to ensure upserts occurred correctly
=> feat: Add snowflake as a destination

lib/connections.ts, lib/snowflake/client.ts, lib/snowflake/load.ts, server/queues/transfer/processor.ts
- Snowflake queries were unreadable and potentially unsafe
- Guarantee safety using the Knex library
- While readability isn't pristine, we can at least rely on the consistent usage of knex.raw
- Manual transfer
=> fix: Knexify snowflake

.github/workflows/readme.yaml, server/routes/views/index.ts, spec.json
=> Hotfix schema template in view create endpoint

.github/workflows/ci.yml, .husky/commit-msg, commitlint.config.cjs, package-lock.json, package.json
- Commit hooks don't run on remote so using --no-verify bypasses checks
- Commitlint runs on remote but not locally
- Added workflow equivalent for pre-commit hooks
- Added commitlint commit-msg hook to husky config
- Ran test commits with varying configurations
=> ci: add commitlint and pre-commit steps to workflows

.github/pull_request_template.md
=> feat: adding pull request links to issues

.github/workflows/update_s3.yml, deploy/configs/versions.json, server/routes/configurations/index.ts, server/routes/destinations/index.ts, server/routes/sources/index.ts, server/routes/transfers/index.ts, server/routes/views/index.ts, server/routes/webhooks/index.ts
Fixes #77, and fixes #88
Refactored to descending order.
Added env to git workflow for update_s3
=> refactor: added orderby createdAt in descending order to list endpoints

lib/aws/upload.ts, lib/connections.ts, lib/load/index.ts, lib/redshift/load.ts, lib/share/index.ts, lib/snowflake/client.ts, lib/snowflake/load.ts, lib/temporal/activities.ts, migrations/20220908180910_add_warehouse_to_destination/migration.sql, schema.prisma, server/routes/destinations/index.ts, server/routes/shares/index.ts, server/routes/transfers/index.ts, spec.json
=> fix: improve tear down and error handling for loads

lib/aws/upload.ts, lib/connections.ts, lib/load/index.ts, lib/redshift/load.ts, lib/share/index.ts, lib/snowflake/client.ts, lib/snowflake/load.ts, lib/temporal/activities.ts, lib/temporal/workflows.ts, migrations/20220908180910_add_warehouse_to_destination/migration.sql, schema.prisma, server/routes/destinations/index.ts, server/routes/shares/index.ts, server/routes/transfers/index.ts, spec.json
=> fix: set up webhooks with temporal

lib/env.ts
=> refactor: added default license key to env.ts

.github/ISSUE_TEMPLATE/feature_request.md
=> chore: updating ISSUE_TEMPLATE

deploy/configs/versions.json, docker-compose.yml
Fixes #96
Pipebird agent needs [admin-ui](https://github.com/pipebird/admin-ui)
Added admin-ui to docker-compose
Ran locally
=> feat: added pipebird-admin-ui service to port 375

deploy/aws/cloudformation/pipebird_existing_cloud_deploy.json, deploy/aws/cloudformation/pipebird_simple_deploy.json
#74 
Moved pipebird folder from /pipebird -> /home/ubuntu/pipebird
=> build: moved pipebird to home dir in ec2

deploy/aws/cloudformation/pipebird_existing_cloud_deploy.json, deploy/aws/cloudformation/pipebird_simple_deploy.json
Previously when docker was failing due to insufficient storage space, we increased the volume size from 8GB -> 50GB. This was likely an over correction
Decreased volume size from 50GB -> 20GB
=> build: changed volume size from 50GB -> 20GB

package-lock.json, package.json, server/app.ts, server/routes/destinations/index.ts
=> fix: add cors for admin UI

README.md
=> chore: Update README copy

RELEASING.md
=> chore: added releasing.md

server/routes/destinations/index.ts, server/routes/sources/index.ts, spec.json
=> feat: add patch route for sources

deploy/aws/cloudformation/pipebird_existing_cloud_deploy.json, deploy/aws/cloudformation/pipebird_simple_deploy.json
Secret keys currently are of length 64 but should have a prefix sk_
=> Fix admin UI

deploy/aws/cloudformation/pipebird_existing_cloud_deploy.json, deploy/aws/cloudformation/pipebird_simple_deploy.json
AWS_REGION was being duplicated in .env.
Also need log tracing on deployments for debugging.
=> refactor: added log level and fixed duplicate aws_region

schema.prisma
Created credential table, merged SourceType and DestinationType into a single enum
=> refactor: added credential table

spec.json
=> chore: update spec for bq dest creation
